### ISSUE TITLE
load/save background

### ISSUE THREAD

**Issue by robotconscience** [labatrockwell/openTSPS#2]
add loading and saving functions for captured background(s)

**Comment by mattfelsen** [comment]
Whoa, this is an old issue! This is still outstanding right? I don't see it in `master` and am having trouble getting `TSPS_1.4` to compile (on OF 0.8.4 – does it require 0.9?). If so I think I can get this worked in over the upcoming weeks :sunglasses:

**Comment by robotconscience** [comment]
It's ancient, for sure!

Yes, I'm not sure on the state of 1.4. I've been waiting for .9 to shake out, think I started it while things were verrrry much in flux. Can probably take a look at it next week?

Would love to chat architecture + dreams if you're open to it! Could be simple stuff, e.g. "get those addons out of that folder" to ways to make the Source API more accessible, making CV filters more plug-and-play, etc. Let me know what you think!

**Comment by mattfelsen** [comment]
Hey yea, would be up to talk about this! Hit me up. I'll add a quick one to the list: Spout for Windows

**Comment by mattfelsen** [comment]
I think this can be closed now that https://github.com/labatrockwell/openTSPS/pull/87 is merged in!

**Comment by robotconscience** [comment]
:+1:
