### ISSUE TITLE
Support video stream capture 

### ISSUE THREAD

**Issue by mandria** [labatrockwell/openTSPS#24]
it could be interesting to get a stream insetad of live cam, it could be made with a reference movie to use the quicktime support to get the stream or get a stream via ip directly

**Comment by jmarsico** [comment]
was this fork ever posted? i'm interested in doing the same thing, but if it's already been done i'd like to check it out. if not, what's the best place in the codebase to get started?

**Comment by robotconscience** [comment]
Hello! It doesn't look like he posted that fork. What you'd need to do is extend ofxTSPS::Source and provide pixels for your source via getPixels() and getPixelsRef(). Check out he OpenNI2 source as a reference:
https://github.com/labatrockwell/openTSPS/blob/master/addons/ofxTSPS/libs/ofxTSPS/include/ofxTSPS/source/OpenNI2.h

If the class you're extending already wraps those, such as ofVideoGrabber, your class will look more like ofxTSPS::VideoFile:
https://github.com/labatrockwell/openTSPS/blob/master/addons/ofxTSPS/libs/ofxTSPS/include/ofxTSPS/source/VideoFile.h

From there, you just have to call "setSource" on your TSPS object and pass a pointer to your custom source:
```
    // call open on your custom source
    source.openSource(320,240 );
        
    // add your custom source, assuming "peopleTracker" is ofxTSPS::PeopleTracker
    peopleTracker.setSource(source);
```

In the TSPS standalone apps, your ofApp simple extends TSPS::Delegate, which sets up and includes peopleTracker like above.

Let me know if you have more questions! Hope the quick intro is helpful.
