### ISSUE TITLE
Update tsps.cc with new Processing 3 version

### ISSUE THREAD

**Issue by grauwald** [labatrockwell/openTSPS#94]
So, just spent the last couple days trying to update the Processing library to 3.0 compatible (I'm an artist not a comp sci major!) and then discovered that the TSPS lib had been updated to Processing 3.  And it works great!

Might be useful to update this page with the Processing 3 version so others can avoid this pitfall:

[http://www.tsps.cc/tutorials/2012/11/4/tsps-processing](http://www.tsps.cc/tutorials/2012/11/4/tsps-processing)

Cheers,
Joseph Gray
http://grauwald.com

**Comment by robotconscience** [comment]
Good catch! Updated 👍

**Comment by grauwald** [comment]
Sweet!
