### ISSUE TITLE
Resurrecting the project for oF 0.9.x and macOS 10.2

### ISSUE THREAD

**Issue by anselanza** [labatrockwell/openTSPS#98]
I think the openTSPS addon is still extremely useful (at least I can say for sure that I need it), but it seems to be a little neglected lately.

I'm busy trying to get things working on oF 0.9.8 and macOS 10.12.6, but running into a few troubles.

So far, I've had to change some instances of `.getPixels()` to `.getPixels().getData()` (which is presumably a change from oF 0.8 to 0.9?) but then getting a whole bunch of build errors relating to `getPixelsRef()`.

Anyone out there willing to help out?

**Comment by robotconscience** [comment]
Hey @anselanza! Yes, I have sadly not had a ton of time to keep up TSPS, but super excited you're digging into it.

Can you post the errors you're getting?

Also, I believe you're going to want to change getPixelsRef() -> getPixels(), as well
